USE AdventureWorks;

ALTER TABLE Sales.MediaOutlet 
ADD CONSTRAINT IX_MEDIAOUTLET 
UNIQUE CLUSTERED (MediaOoutletId);


CREATE CLUSTERED INDEX CIX_PRINTMEDIAPLACEMENT 
ON Sales.PrintMediaPlacement (PrintMediaPlacementId ASC);


CREATE NONCLUSTERED INDEX NCIX_PRINTMEDIAPLACEMENT_NAME 
ON Sales.PrintMediaPlacement (PlacementDate ASC);